### ISSUE TITLE
Build::getConsoleTextBuild error

### ISSUE THREAD

**Issue by Borales** [chbiel/jenkins-php-api#7]
It's impossible to get "console output" for the selected build via the `\JenkinsApi\Item\Build::getConsoleTextBuild` method.

https://github.com/chbiel/jenkins-php-api/blob/master/src/JenkinsApi/Item/Build.php#L225

The problem is that `\JenkinsApi\Jenkins::get` method tries to process the response data with the `json_decode` function and throws an exception (because received data is a plain text)

https://github.com/chbiel/jenkins-php-api/blob/master/src/JenkinsApi/Jenkins.php#L166

---

Maybe we could add additional parameter to the `\JenkinsApi\Jenkins::get` method like `$raw = false` and run the `json_decode` function depending on this parameter?

```
public function get($url, $depth = 1, $params = array(), array $curlOpts = [], $raw = false)
```

**Comment by chbiel** [comment]
Thanks for the fix
